- name: Create a VM from a template
  hosts: localhost
  gather_facts: no
  connection: local
  tasks:
  - name: Clone the template
    vmware_guest:
      hostname: {{vcenter_ip}}
      username: {{vcenter_username}}
      password: {{vcenter_pass}}
      validate_certs: False
      name: testdeploiment
      template: "CoreOsmodele"
      datacenter: "projetM1"
      folder: "Modeletest"
      state: poweredon
      wait_for_ip_address: yes
